/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViaScoreRouteImport } from './routes/via-score'
import { Route as ViaMethodRouteImport } from './routes/via-method'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ImmersiveRouteImport } from './routes/immersive'
import { Route as ExecutiveBriefingRouteImport } from './routes/executive-briefing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CognitiveWireframeRouteImport } from './routes/cognitive-wireframe'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ViaScoreRoute = ViaScoreRouteImport.update({
  id: '/via-score',
  path: '/via-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ViaMethodRoute = ViaMethodRouteImport.update({
  id: '/via-method',
  path: '/via-method',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersiveRoute = ImmersiveRouteImport.update({
  id: '/immersive',
  path: '/immersive',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveBriefingRoute = ExecutiveBriefingRouteImport.update({
  id: '/executive-briefing',
  path: '/executive-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveWireframeRoute = CognitiveWireframeRouteImport.update({
  id: '/cognitive-wireframe',
  path: '/cognitive-wireframe',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/cognitive-wireframe': typeof CognitiveWireframeRoute
  '/dashboard': typeof DashboardRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/immersive': typeof ImmersiveRoute
  '/simulation': typeof SimulationRoute
  '/via-method': typeof ViaMethodRoute
  '/via-score': typeof ViaScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/cognitive-wireframe': typeof CognitiveWireframeRoute
  '/dashboard': typeof DashboardRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/immersive': typeof ImmersiveRoute
  '/simulation': typeof SimulationRoute
  '/via-method': typeof ViaMethodRoute
  '/via-score': typeof ViaScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/cognitive-wireframe': typeof CognitiveWireframeRoute
  '/dashboard': typeof DashboardRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/immersive': typeof ImmersiveRoute
  '/simulation': typeof SimulationRoute
  '/via-method': typeof ViaMethodRoute
  '/via-score': typeof ViaScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-study'
    | '/cognitive-wireframe'
    | '/dashboard'
    | '/executive-briefing'
    | '/immersive'
    | '/simulation'
    | '/via-method'
    | '/via-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-study'
    | '/cognitive-wireframe'
    | '/dashboard'
    | '/executive-briefing'
    | '/immersive'
    | '/simulation'
    | '/via-method'
    | '/via-score'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-study'
    | '/cognitive-wireframe'
    | '/dashboard'
    | '/executive-briefing'
    | '/immersive'
    | '/simulation'
    | '/via-method'
    | '/via-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudyRoute: typeof CaseStudyRoute
  CognitiveWireframeRoute: typeof CognitiveWireframeRoute
  DashboardRoute: typeof DashboardRoute
  ExecutiveBriefingRoute: typeof ExecutiveBriefingRoute
  ImmersiveRoute: typeof ImmersiveRoute
  SimulationRoute: typeof SimulationRoute
  ViaMethodRoute: typeof ViaMethodRoute
  ViaScoreRoute: typeof ViaScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/via-score': {
      id: '/via-score'
      path: '/via-score'
      fullPath: '/via-score'
      preLoaderRoute: typeof ViaScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/via-method': {
      id: '/via-method'
      path: '/via-method'
      fullPath: '/via-method'
      preLoaderRoute: typeof ViaMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immersive': {
      id: '/immersive'
      path: '/immersive'
      fullPath: '/immersive'
      preLoaderRoute: typeof ImmersiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-briefing': {
      id: '/executive-briefing'
      path: '/executive-briefing'
      fullPath: '/executive-briefing'
      preLoaderRoute: typeof ExecutiveBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-wireframe': {
      id: '/cognitive-wireframe'
      path: '/cognitive-wireframe'
      fullPath: '/cognitive-wireframe'
      preLoaderRoute: typeof CognitiveWireframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudyRoute: CaseStudyRoute,
  CognitiveWireframeRoute: CognitiveWireframeRoute,
  DashboardRoute: DashboardRoute,
  ExecutiveBriefingRoute: ExecutiveBriefingRoute,
  ImmersiveRoute: ImmersiveRoute,
  SimulationRoute: SimulationRoute,
  ViaMethodRoute: ViaMethodRoute,
  ViaScoreRoute: ViaScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
